### ISSUE TITLE
f-string error on python 3.5

### ISSUE THREAD

**Issue by roomylee** [pingpong-ai/chatspace#19]
https://github.com/pingpong-ai/chatspace/blob/15d0ede394b696d293ddbe0f0424b45978a29371/chatspace/data/vocab.py#L197

python 3.5에 대한 처리가 필요합니다.

**Comment by sjkoo1989** [comment]
저는 어차피 Python 3.5 는 legacy 버전이니까 3.5에 대한 별도의 처리보다는 아예 사양을 3.6 이상으로 명시하는 것이 좋겠습니다.

**Comment by jeongukjae** [comment]
3.5가 EOL이 1년 남은만큼 저도 3.6으로 명시하는 것이 좋아보입니다.

**Comment by jeongukjae** [comment]
https://github.com/pingpong-ai/chatspace/blob/5cb7b8b884158ceec83b7e68758594d6819b86b6/setup.py#L18

**Comment by jeongukjae** [comment]
이미 3.6 이상으로 명시되어 있기 때문에 해당 이슈는 close하겠습니다
