### ISSUE TITLE
개인적으로 모델 만들고 싶으면. train.py  구동하면되나요??

### ISSUE THREAD

**Issue by ssifood** [pingpong-ai/chatspace#21]
chatspace가 좋아보여서
개인적인 모델을 만들어서 사용하고 싶어졌습니다.

그래서 train.py를 돌리니
outputs/checkpoints
outputs/jit_models
outputs/models 폴더를 수동으로 만들어 돌리고 있습니다.

이러면 될꺄용???

**Comment by sjkoo1989** [comment]
안녕하십니까?
스캐터랩의 ML 엔지니어 구상준입니다.

말씀하신대로 출력 폴더를 수동으로 만들어서 돌리시면 되는 것으로 압니다.
담당자가 2주간 장기 출장 중에 있어서 지금 바로 정확하게 답변드릴 수 없는 점 죄송합니다.
담당자가 돌아오면 바로 문의하도록 하겠습니다.
