### ISSUE TITLE
사용자 사전 기능 추가 부탁 드립니다.

### ISSUE THREAD

**Issue by bestend** [pingpong-ai/chatspace#24]
신조어나 서비스 용어에 강건해질수 있도록 
사용자 사전을 입력받아서 띄어쓰기 모듈에 예외처리나 특징으로 사용하는것은 어떨까요?

**Comment by sjkoo1989** [comment]
안녕하십니까?
스캐터랩의 ML 엔지니어 구상준입니다.

말씀하신대로 사용자 사전을 넣으면 훨씬 뛰어난 모듈을 만들 수 있습니다.
실제로 상당수의 오류는 훈련 셋에 없는 개체명에서 발생하였습니다.
다만 현재로써는 버그 수정을 제외한 코드의 개선 계획이 없습니다.

담당자가 업무에서 돌아오는대로 논의를 해보도록 하겠습니다.

**Comment by codertimo** [comment]
@bestend 안녕하세요 스캐터랩의 ML엔지니어 김준성입니다.
우선 요청사항 처리가 늦은 점에 대해서 사과의 말씀을 드립니다.

해당 내용 확인하였으며, 빠른 시일내에 요청 주신 부분 반영이 가능하도록 개발을 진행하도록 하겠습니다.
저희 팀 내에서도 말씀주신 내용와 동일한 니즈를 갖고 있어 빠르게 개발을 진행하고자 합니다.

좋은 제안주셔서 감사합니다. 👍
