### ISSUE TITLE
PR #27 업데이트 내용을 반영한 패키지가 버젼 업이 되지 않았음

### ISSUE THREAD

**Issue by codertimo** [pingpong-ai/chatspace#30]
## 무엇이 문제인가요?

- PR #27 에서 사용자 사전 기능이 추가 되었는데, 이 내용 변경 이후에 chatspace 버전이 올라가지 않았음
- 변경 이후 pip 에 업데이트된 패키지가 올라가지 않아, #27 업데이트를 사용하려면 git repo 를 통해 설치해야함

**Comment by ZiminPark** [comment]
지금도 pip으로 설치하면 1.0.1 버전으로 설치되는 게 맞나요?
