### ISSUE TITLE
Windows에서 pip 오류

### ISSUE THREAD

**Issue by mybirth0407** [pingpong-ai/chatspace#6]
Windows 10에서 
pip install git+https://github.com/pingpong-ai/chatspace#egg=chatspace
명령어로 설치를 시도할 경우 
UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 301: illegal multibyte sequence
에러가 발생합니다.

현재 Linux 계열만 설치가 가능한 건가요?

**Comment by codertimo** [comment]
안녕하세요 @mybirth0407 님

말씀주신 문제는 window 문제보다는 python3.x 버젼을 사용하지 않아서 발생한 문제인 것 같습니다. python3.6 또는 python3.7 사용을 권장드립니다.

**Comment by mybirth0407** [comment]
python 3.6버전을 사용하고 있고, windows 10 영문버전에서는 설치가 되는 걸 확인했습니다.
아마 패키지 내의 유니코드 관련한 문제 같은데, 혹시 windows 한글에서 말씀해주신 python 3.6 혹은 3.7 버전으로 테스트가 되었는지 궁금합니다.

**Comment by ByungjunKim** [comment]
저도 같은 증상이 일어나네요. 급한대로 WSL로 리눅스 설치를 했습니다.
