### ISSUE TITLE
Error while loading model.

### ISSUE THREAD

**Issue by hsh2438** [pingpong-ai/chatspace#7]
torch version: 1.0.1
python: 3.7.1 (anaconda)
os: ubuntu 16.04
cuda version: 9.0

from chatspace import ChatSpace
spacer = ChatSpace()

Loading JIT Compiled ChatSpace Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.7/site-packages/chatspace/inference.py", line 48, in __init__
    self.model = self._load_model(model_path, self.device, from_jit=from_jit)
  File "/root/anaconda3/lib/python3.7/site-packages/chatspace/inference.py", line 164, in _load_model
    model = self._load_model_from_jit(model_path)
  File "/root/anaconda3/lib/python3.7/site-packages/chatspace/inference.py", line 196, in _load_model_from_jit
    model = torch.jit.load(model_path)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 132, in load
    torch._C.import_ir_module(module_lookup, f, map_location)
RuntimeError: INVALID_ARGUMENT:main_module.submodules[5]: Cannot find field. (deserialize at /pytorch/torch/csrc/jit/import.cpp:95)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fa1dc634021 in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fa1dc6338ea in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x669351 (0x7fa1dbaa9351 in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #3: torch::jit::import_ir_module(std::function<std::shared_ptr<torch::jit::script::Module> (std::vector<std::string, std::allocator<std::string> > const&)>, std::string const&, c10::optional<c10::Device>) + 0x107 (0x7fa1dbaa9c27 in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x3a48f1 (0x7fa216c048f1 in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x11663e (0x7fa21697663e in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #32: __libc_start_main + 0xf0 (0x7fa228e7d830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by codertimo** [comment]
Thank you for reporting @hsh2438!

Can you try with under code which disable the jit_model loading?
``` python
from chatspace import ChatSpace
spacer = ChatSpace()
```

**Comment by codertimo** [comment]
It would be work fine if you reinstall the #8 merged version on master branch.
Please reinstall and let me know the result :) 

다시 설치해 주시면 아마 발생하셨던 문제가 자연적으로 해결 될 것 같습니다.
